; This is the module configuration file

[Module_Info]
mod_name = "Tx Fan3"
version = "1.1"
min_orp_ver = "2.2.0"
authors = "Dan Loranger (KG7PAR), Aaron Crawford (N3MBH)"
display_name = "Repeater Exciter Tx Fan"
mod_desc = "MODIFIED. This module allows control of a cooling fan via a GPIO pin. It follows the PTT activity or comes on after a delay. This is a modified version to allow for a third instance of TX Fan."