; This is the module configuration file

[Module_Info]
mod_name = "TxFan"
version = "2.1.x"
min_orp_ver = "2.2.0"
authors = "Dan Loranger (KG7PAR), Aaron Crawford (N3MBH), & Jeff Cacioppo( WB9OUF)"
display_name = "UHF Repeater PA Fan"
mod_desc = "This module allows control of the Repeater's cooling fan via PTT Activity or in extreme cases, excessive temperature"