; This is the module configuration file

[Module_Info]
mod_name = "TxFan2"
version = "2.0"
min_orp_ver = "2.2.0"
authors = "Dan Loranger (KG7PAR), Aaron Crawford (N3MBH), & Jeff Cacioppo (WB9OUF)"
display_name = "Remote Base Fan"
mod_desc = "This module allows control of a cooling fan for the Remote Base via PTT activity"